site_name: humanize
site_url: https://prettytable.readthedocs.io
repo_url: https://github.com/jazzband/prettytable
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

nav:
  - Home: index.md
  - PrettyTable: prettytable.md

plugins:
  - search
  - mkdocstrings:
      watch:
        - src/prettytable
  - include-markdown

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
      pygments_lang_class: true
  - pymdownx.superfences

extra_css:
  - css/code_select.css
